# Generated by Django 4.0.5 on 2022-07-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mpg', models.FloatField()),
                ('cylinders', models.IntegerField()),
                ('displacement', models.FloatField()),
                ('horsepower', models.FloatField()),
                ('weight', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('model', models.IntegerField()),
                ('origin', models.CharField(max_length=200)),
            ],
        ),
    ]
