version: "3.9"

services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    restart: on-failure
    container_name: carslisting-backend
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py runserver"
    ports:
      - "8000:8000"
    volumes:
      - .:/carslisting
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy